"""
Utility functions for code generation and agent loading.

This module contains functions related to generating, cleaning, and loading 
agent code generated by LLM coders.
"""

import os
import sys
import importlib.util
import tempfile
from typing import Optional
from ..agents.base import BaseAgent


def clean_generated_code(code_content: str) -> str:
    """
    Clean markdown code blocks and other artifacts from generated code.
    
    Args:
        code_content: Raw generated code content from LLM
        
    Returns:
        Cleaned code content ready for execution
    """
    lines = code_content.split('\n')
    cleaned_lines = []
    in_code_block = False
    
    for line in lines:
        stripped = line.strip()
        
        # Handle markdown code block markers
        if stripped.startswith('```'):
            if 'python' in stripped.lower():
                in_code_block = True
            elif stripped == '```' and in_code_block:
                in_code_block = False
            continue
        
        # If we're in a markdown code block, include the line
        if in_code_block:
            cleaned_lines.append(line)
    
    # If no markdown code block was found, return the original content
    # (in case the LLM didn't follow the markdown format instruction)
    if not cleaned_lines:
        # Try to extract code by skipping obvious explanatory text
        for line in lines:
            stripped = line.strip()
            # Skip explanatory text at the beginning
            if (stripped.startswith('Below is') or
                stripped.startswith('Here is') or
                stripped.startswith('This is') or
                stripped.startswith('The following')):
                continue
            # Include everything else
            cleaned_lines.append(line)
    
    # Remove trailing empty lines
    while cleaned_lines and not cleaned_lines[-1].strip():
        cleaned_lines.pop()
    
    return '\n'.join(cleaned_lines)


def load_agent_from_file(code_file: str, agent_name: str) -> Optional[BaseAgent]:
    """
    Dynamically load agent class from generated code file.
    
    This function handles loading agent code generated by LLM coders,
    including cleaning the code and creating agent instances.
    
    Args:
        code_file: Path to the code file containing agent implementation
        agent_name: Name to assign to the loaded agent
        
    Returns:
        Loaded agent instance or None if loading failed
    """
    try:
        # Check if file exists
        if not os.path.exists(code_file):
            print(f"File not found: {code_file}")
            return None
        
        # Read and clean the code
        with open(code_file, 'r', encoding='utf-8') as f:
            original_code = f.read()
        
        cleaned_code = clean_generated_code(original_code)
        
        # Write cleaned code to temporary file (UTF-8 — see explanation in
        # tournament_manager._generate_and_test_single_coder_enhanced).
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', suffix='.py', delete=False) as temp_file:
            temp_file.write(cleaned_code)
            temp_file_path = temp_file.name
        
        try:
            # Load module from cleaned file
            spec = importlib.util.spec_from_file_location(f"{agent_name}_module", temp_file_path)
            if spec is None or spec.loader is None:
                print(f"Failed to create module spec for {code_file}")
                return None
                
            module = importlib.util.module_from_spec(spec)
            
            # Add ProxyWar to sys.path for imports
            # Navigate to the root directory from coders/utils.py
            current_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            if current_dir not in sys.path:
                sys.path.insert(0, current_dir)
            
            spec.loader.exec_module(module)
            
            # Find agent class in the module
            agent_class = None
            for attr_name in dir(module):
                attr = getattr(module, attr_name)
                if (isinstance(attr, type) and 
                    hasattr(attr, 'select_action') and 
                    attr.__name__ != 'BaseAgent'):
                    agent_class = attr
                    break
            
            if agent_class:
                # Create instance
                agent_instance = agent_class(agent_name)
                print(f"Successfully loaded agent: {agent_class.__name__}")
                return agent_instance
            else:
                print(f"No valid agent class found in {code_file}")
                return None
                
        finally:
            # Clean up temporary file
            os.unlink(temp_file_path)
            
    except Exception as e:
        print(f"Failed to load agent from {code_file}: {e}")
        import traceback
        traceback.print_exc()
        return None 